// ================================================================
// TestCase Studio — Playwright Script
// Name  : Recorded_Test
// Date  : 21/7/2026, 12:09:23 p. m.
// Steps : 20
// ================================================================
// RUN:
//   npm install && npx playwright install chromium
//   node Recorded_Test.spec.js
// ================================================================
// LOCATOR STRATEGY per element step (tried in order):
//   1. Primary XPath (recorded)
//   2. Primary CSS   (recorded)
//   3. Index-based XPath   e.g. (//button)[4]
//   4. Text-based XPath    e.g. //button[normalize-space()="OK"]
//   5. Partial-ID XPath    e.g. //input[contains(@id,"field-")]
// ================================================================

'use strict';
const { chromium } = require('playwright');

// ─── findElement: tries every locator in order, first match wins ────────────
// Generated by TestCase Studio. Handles dynamic IDs automatically.
async function findElement(locators, stepDesc) {
  const errs = [];
  for (const { label, loc } of locators) {
    try {
      await loc.waitFor({ state: 'attached', timeout: 3000 });
      if (await loc.count() > 0) {
        process.stdout.write('  [✓] ' + stepDesc + ' → ' + label + '\n');
        return loc.first();
      }
      errs.push(label + ': 0 elements matched');
    } catch (e) {
      errs.push(label + ': ' + e.message.split('\n')[0]);
    }
  }
  throw new Error(
    'Element not found for: "' + stepDesc + '"\n' +
    errs.map((e, i) => '  ' + (i + 1) + '. ' + e).join('\n') + '\n' +
    'Tip: Re-record this step if the page structure changed.'
  );
}
// ─────────────────────────────────────────────────────────────────────────────

(async () => {
  const browser = await chromium.launch({ headless: false, slowMo: 80 });
  const context = await browser.newContext();
  const page    = await context.newPage();

  // ── 20 Recorded Steps ─────────────────────────────────────

  // Step 1: Open website
  await page.goto('https://www.mercadolibre.com.co/');

  // Step 2: Enter "alicate" into "Ingresa lo que quieras encontrar"
  // Playwright: page.locator('#cb1-edit')
  const el_2 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//input[@id=\'cb1-edit\']') },
    { label: 'CSS (primary)', loc: page.locator('#cb1-edit') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//input)[1]') },
    { label: 'nth-of-type CSS', loc: page.locator('input:nth-of-type(1)') }
  ], 'Enter "alicate" into "Ingresa lo que quieras encontrar"');
  await el_2.fill(`alicate`);

  // Step 3: Press Enter
  // Playwright: page.locator('#cb1-edit')
  const el_3 = await findElement([
    { label: 'CSS (primary)', loc: page.locator('#cb1-edit') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//input)[1]') },
    { label: 'nth-of-type CSS', loc: page.locator('input:nth-of-type(1)') }
  ], 'Press Enter');
  await el_3.press('Enter');

  // Step 4: Click on "1 de 6"
  // Playwright: page.locator('body > main:nth-child(8) > div:nth-child(1) > div:nth-child(2) > section:nth-child(2) > ol:nth-child(2) > li:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > section:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > a:nth-child(1) > span:nth-child(1)')
  const el_4 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//div[@aria-label=\'1 de 6\']//span[@class=\'poly-component__image-overlay\']') },
    { label: 'CSS (primary)', loc: page.locator('body > main:nth-child(8) > div:nth-child(1) > div:nth-child(2) > section:nth-child(2) > ol:nth-child(2) > li:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > section:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > a:nth-child(1) > span:nth-child(1)') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//span)[98]') },
    { label: 'nth-of-type CSS', loc: page.locator('span:nth-of-type(1)') }
  ], 'Click on "1 de 6"');
  await el_4.click();

  // Step 5: Reload
  await page.reload();

  // Step 6: Scroll down
  await page.evaluate(() => window.scrollBy(0, 400));

  // Step 7: Scroll up
  await page.evaluate(() => window.scrollBy(0, -400));

  // Step 8: Click on "Kit De Herramientas 5 En 1 Multiusos"
  // Playwright: page.locator('.ui-pdp-title')
  const el_8 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//h1[normalize-space()=\'Kit De Herramientas 5 En 1 Multiusos\']') },
    { label: 'CSS (primary)', loc: page.locator('.ui-pdp-title') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//h1)[1]') },
    { label: 'nth-of-type CSS', loc: page.locator('h1:nth-of-type(1)') }
  ], 'Click on "Kit De Herramientas 5 En 1 Multiusos"');
  await el_8.click();

  // Step 9: Scroll down
  // Playwright: page.locator('h1')
  await page.evaluate(() => window.scrollBy(0, 400));

  // Step 10: Click on "$30.000"
  // Playwright: page.locator('#_r_0_')
  const el_10 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//span[@id=\'_r_0_\']') },
    { label: 'CSS (primary)', loc: page.locator('#_r_0_') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//span)[97]') },
    { label: 'Text-based XPath', loc: page.locator('xpath=//span[normalize-space()=\'$ 30.000\']') },
    { label: 'nth-of-type CSS', loc: page.locator('span:nth-of-type(1)') }
  ], 'Click on "$30.000"');
  await el_10.click();

  // Step 11: Click on "Vendido porTITUIMPORTACIONESMercadoLíder | +1000 ventas"
  // Playwright: page.locator('.ui-pdp-seller-summary.mt-24')
  const el_11 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//div[@class=\'ui-pdp-seller-summary mt-24\']') },
    { label: 'CSS (primary)', loc: page.locator('.ui-pdp-seller-summary.mt-24') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//div)[189]') },
    { label: 'Text-based XPath', loc: page.locator('xpath=//div[normalize-space()=\'Vendido por TITUIMPORTACIONES MercadoLíder | +1000 ventas\']') },
    { label: 'nth-of-type CSS', loc: page.locator('div:nth-of-type(1)') }
  ], 'Click on "Vendido porTITUIMPORTACIONESMercadoLíder | +1000 ventas"');
  await el_11.click();

  // Step 12: Scroll up
  // Playwright: page.locator('div')
  await page.evaluate(() => window.scrollBy(0, -400));

  // Step 13: Click on "4.8Calificación 4.8 de 5. 12 opiniones.(12)"
  // Playwright: page.locator('.ui-pdp-header__product-classification')
  const el_13 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//div[@class=\'ui-pdp-header__product-classification\']') },
    { label: 'CSS (primary)', loc: page.locator('.ui-pdp-header__product-classification') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//div)[56]') },
    { label: 'Text-based XPath', loc: page.locator('xpath=//div[normalize-space()=\'4.8 Calificación 4.8 de 5. 12 opiniones. (12)\']') },
    { label: 'nth-of-type CSS', loc: page.locator('div:nth-of-type(2)') }
  ], 'Click on "4.8Calificación 4.8 de 5. 12 opiniones.(12)"');
  await el_13.click();

  // Step 14: Scroll down
  // Playwright: page.locator('div')
  await page.evaluate(() => window.scrollBy(0, 400));

  // Step 15: Scroll up
  await page.evaluate(() => window.scrollBy(0, -400));

  // Step 16: Scroll down
  await page.evaluate(() => window.scrollBy(0, 400));

  // Step 17: Scroll up
  await page.evaluate(() => window.scrollBy(0, -400));

  // Step 18: Scroll down
  await page.evaluate(() => window.scrollBy(0, 400));

  // Step 19: Click on "Llega gratis mañana por ser tu primera compra"
  // Playwright: page.locator('#title_address_0')
  const el_19 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//div[@id=\'title_address_0\']') },
    { label: 'CSS (primary)', loc: page.locator('#title_address_0') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//div)[164]') },
    { label: 'Text-based XPath', loc: page.locator('xpath=//div[normalize-space()=\'Llega gratis mañana por ser tu primera compra\']') },
    { label: 'nth-of-type CSS', loc: page.locator('div:nth-of-type(1)') }
  ], 'Click on "Llega gratis mañana por ser tu primera compra"');
  await el_19.click();

  // Step 20: Scroll up
  // Playwright: page.locator('div[id=\'title_address_0\']')
  await page.evaluate(() => window.scrollBy(0, -400));

  console.log('\n✓ All 20 steps passed.');
  await browser.close();
})().catch(err => {
  console.error('\n✗ Test failed:', err.message);
  process.exit(1);
});